definitions:
  Book:
    properties:
      author:
        type: string
      id:
        readOnly: true
        type: integer
      title:
        type: string
    required:
      - author
      - title
    type: object
info:
  title: BooksList
  version: 1.0.0
paths:
  /api/books:
    get:
      responses:
        '200':
          description: Books data
          schema:
            items:
              $ref: '#/definitions/Book'
            type: array
      summary: This is an endpoint for obtaining the books list.
      tags:
        - books
    post:
      parameters:
        - in: body
          name: new book params
          schema:
            $ref: '#/definitions/Book'
      responses:
        '201':
          description: The book has been created
          schema:
            $ref: '#/definitions/Book'
        '422':
          description: Validation exception
      summary: This is an endpoint for book creation.
      tags:
        - books
  /api/books/{book_id}:
    get:
      parameters:
        - name: book_id
          in: path
          type: integer
          description: ID of book to return
          required: true
      responses:
        '200':
          description: Data book with ID
          schema:
            items:
              $ref: '#/definitions/Book'
        '400':
          description: Invalid ID suplited
        '404':
          description: Book not found
        '422':
          description: Validation exception
      summary: This is the end point for getting detailed information about the book.
      tags:
        - books
swagger: '2.0'
