{
 "title": "module_24",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pages status 200",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "doors_app_counter_index_total{status=\"200\"}",
     "legendFormat": "index"
    },
    {
     "expr": "doors_app_counter_page_one_total{status=\"200\"}",
     "legendFormat": "page_one"
    },
    {
     "expr": "doors_app_counter_page_two_total{status=\"200\"}",
     "legendFormat": "pahe_two"
    },
    {
     "expr": "doors_app_counter_page_three_total{status=\"200\"} ",
     "legendFormat": "page_three"
    }
   ]
  },
  {
   "title": "Page status 500",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "doors_app_counter_page_two_total{status=\"500\"} ",
     "legendFormat": "page_two"
    },
    {
     "expr": "doors_app_counter_page_three_total{status=\"500\"}",
     "legendFormat": "page_three"
    }
   ]
  },
  {
   "title": "Page status 400",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "doors_app_counter_page_two_total{status=\"400\"}",
     "legendFormat": "page_two"
    },
    {
     "expr": "doors_app_counter_page_three_total{status=\"400\"}",
     "legendFormat": "page_three"
    }
   ]
  }
 ]
}